[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
env = { AQUA_GLOBAL_CONFIG = "/Users/(User)/.config/aquaproj-aqua/aqua.yaml" }

[mcp_servers.figma-dev-mode-mcp-server]
command = "npx"
args = ["-y", "mcp-remote", "http://127.0.0.1:3845/mcp"]
env = { AQUA_GLOBAL_CONFIG = "/Users/(User)/.config/aquaproj-aqua/aqua.yaml" }

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
env = { AQUA_GLOBAL_CONFIG = "/Users/(User)/.config/aquaproj-aqua/aqua.yaml" }

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]
env = { AQUA_GLOBAL_CONFIG = "/Users/(User)/.config/aquaproj-aqua/aqua.yaml" }
