customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with git-cz"
    context: "files"
    loadingText: "opening git-cz commit tool"
    subprocess: true
gui:
  mouseEvents: false
