- name: install cursor extensions
  cursor_extension:
    name: "{{ item }}"
  loop:
    - asvetliakov.vscode-neovim
    - bradlc.vscode-tailwindcss
    - bufbuild.vscode-buf
    - docker.docker
    - esbenp.prettier-vscode
    - golang.go
    - hashicorp.terraform
    - james-yu.latex-workshop
    - leanprover.lean4
    - oxc.oxc-vscode
    - redhat.vscode-yaml
    - unifiedjs.vscode-mdx
    - vue.volar
